### ISSUE TITLE
Light color theme has some unreadable color combinations

### ISSUE THREAD

**Issue by burnsba** [decompme/decomp.me#678]
Precondition: choose light theme and set background color to white.

The CTRL+F search popup now has white-on-white text to label the checkboxes "match case, regexp, by word"

![image](https://user-images.githubusercontent.com/1695783/218235316-3b3e398c-01c0-480d-bd46-75f51cd38f02.png)

There are several illegible diff colors as well. Here is light blue and light pink, I believe it is possible to get either white or light grey as well:

![image](https://user-images.githubusercontent.com/1695783/218235350-1a359390-d883-4278-b031-5e8bcc89f5ea.png)

**Comment by conorgolden1** [comment]
I believe this was fixed in #797

**Comment by burnsba** [comment]
I created a new scratch, firefox still shows this as white on white

![image](https://github.com/decompme/decomp.me/assets/1695783/4158d604-bdb9-44ff-9b01-3b02f5cc143c)

**Comment by conorgolden1** [comment]
That is because I believe the live site hasn't migrated from the repo yet because the pr #1223 was merged into main 6 hours ago that fixes that issue
